//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gordon360.Models
{
    using System;
    using System.Collections.Generic;

    public class VictoryPromise
    {
        public int TOTAL_VP_IM_SCORE { get; set; }
        public int TOAL_VP_CC_SCORE { get; set; }
        public int TOTAL_VP_LS_SCORE { get; set; }
        public int TOTAL_VP_LW_SCORE { get; set; }
    }
}